export const GET_PATIENT = 'GET_PATIENT';
export const GET_PATIENTS = 'GET_PATIENTS';
export const CREATE_PATIENT = 'CREATE_PATIENT';
export const UPDATE_PATIENT = 'UPDATE_PATIENT';
export const DELETE_PATIENT = 'DELETE_PATIENT';